# Generated by Django 5.1.4 on 2024-12-08 19:19

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.ImageUploadPaths.thumbnail,
                    ),
                ),
                (
                    "mobile",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.ImageUploadPaths.mobile,
                    ),
                ),
                (
                    "tablet",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.ImageUploadPaths.tablet,
                    ),
                ),
                (
                    "desktop",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.ImageUploadPaths.desktop,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
