# Generated by Django 5.1.4 on 2024-12-08 20:18

import config.storage
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productimageset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimageset",
            name="desktop",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.OVERWRITE_STORAGE,
                upload_to=shop.models.ImageUploadPaths.desktop,
            ),
        ),
        migrations.AlterField(
            model_name="productimageset",
            name="mobile",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.OVERWRITE_STORAGE,
                upload_to=shop.models.ImageUploadPaths.mobile,
            ),
        ),
        migrations.AlterField(
            model_name="productimageset",
            name="tablet",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.OVERWRITE_STORAGE,
                upload_to=shop.models.ImageUploadPaths.tablet,
            ),
        ),
        migrations.AlterField(
            model_name="productimageset",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.OVERWRITE_STORAGE,
                upload_to=shop.models.ImageUploadPaths.thumbnail,
            ),
        ),
    ]
